FROM ruby:3.1.2

ARG NODE_MAJOR_VERSION=19
RUN curl -sL https://deb.nodesource.com/setup_${NODE_MAJOR_VERSION}.x | bash - 
RUN apt-get update -qq && \
    apt-get install -y build-essential libvips libpq-dev postgresql-client && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /usr/share/doc /usr/share/man 

WORKDIR /api
ADD . /api
RUN gem install bundler -v 2.3.7
RUN bundle install




